[package]
name = "BJKS"
version = "1.0.1"
description = "本机快搜 - Windows 本地文件快速搜索工具"
authors = ["hanwu-git"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
glob = "0.3"
rayon = "1"
chrono = "0.4"
walkdir = "2"
dirs = "5"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = "s"          # 优化体积
lto = true               # 链接时优化
codegen-units = 1        # 单代码生成单元，进一步优化
panic = "abort"          # 移除 panic 展开代码
strip = true             # 去除符号表